### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by howardre** [howardre/ORnearshore_groundfish#1]

**Comment by Juniper41** [comment]
Hi Rebecca! I was unable to see your PPT due to internet difficulties, but I think the idea of streamlining your R code and having the same code for various species is a great idea. I currently work with a short list of species and having the same code makes it very easy to swap out species and run analysis.

**Comment by Coffee-Powered-Scientist** [comment]
Very nice presentation, good visuals and explanation of your challenges.

**Comment by jwongala** [comment]
Hey I enjoyed your presentation. You challenges are very similar to my own so it would be great to chat about it some time.

**Comment by jessealaney** [comment]
Hi Rebecca! You seem to have a good grasp on your data sets concerning their inherent structure and some of the issues associated with them. Is there a way you can automate drawing the polygons? Have you considered trying to automate a convex hull, for example?

**Comment by zechmeunier** [comment]
Sounds like a cool project! Will you work directly with the fishing industry or only through ODFW?

**Comment by JenningsJC** [comment]
I liked the background pics and the way your slides were laid out, easy to read.

**Comment by breshears-logan** [comment]
I liked how you presented the material in a way that is easy to understand and follow along. The layout was nice and simple! Would you be able to expand this research outside of ODFW?

**Comment by McLeodMJ** [comment]
Hi Rebecca! I'm really glad to learn about your project, there looks to be quite a bit of crossover with my project and we have similar backgrounds, so I am with you on the challenges! I have found working in Rmarkdown was a good way to organize multiple species I am working with. If it is similar enough code, I often create a function where I can change the species for different outputs and then create the graphics afterwards. Great presentation!

**Comment by Angelika-Kurthen** [comment]
Hi Rebecca, 

I wasn't able to see all of the visuals in your presentation because of bad internet, but I enjoyed the audio version of your presentation. I can totally sympathize with your issue of data confidentiality - some of the data I'm working with is from DoD land, so any of the photos we take are confidential. Additionally, I can also understand the difficulty of working with data gathered from a large number of different people. I can't wait to see how your project progresses.
